
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.tnunlimited.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.tnunlimited.item.ZombieSwordItem;
import net.mcreator.tnunlimited.item.ZincSheetItem;
import net.mcreator.tnunlimited.item.ZincIngotItem;
import net.mcreator.tnunlimited.item.ZincArmorItem;
import net.mcreator.tnunlimited.item.WrathsDeathCryItem;
import net.mcreator.tnunlimited.item.WoodenSickleItem;
import net.mcreator.tnunlimited.item.WitherAndRotItem;
import net.mcreator.tnunlimited.item.WitherAndRotChiptuneItem;
import net.mcreator.tnunlimited.item.WitchItem;
import net.mcreator.tnunlimited.item.WeatherClockItem;
import net.mcreator.tnunlimited.item.WarcasterItem;
import net.mcreator.tnunlimited.item.VillagerNoseItem;
import net.mcreator.tnunlimited.item.VambraceItem;
import net.mcreator.tnunlimited.item.TwoLayerHelmetItem;
import net.mcreator.tnunlimited.item.TreeBarkItem;
import net.mcreator.tnunlimited.item.TreeBarkDiscItem;
import net.mcreator.tnunlimited.item.TrainItem;
import net.mcreator.tnunlimited.item.TorchOfGuidanceItem;
import net.mcreator.tnunlimited.item.TopHatItem;
import net.mcreator.tnunlimited.item.TitaniumItem;
import net.mcreator.tnunlimited.item.TinySelfDetonatorItem;
import net.mcreator.tnunlimited.item.ThickHorseshoeItem;
import net.mcreator.tnunlimited.item.TheDragonGuardingTheAbyssItem;
import net.mcreator.tnunlimited.item.SwordSaberItem;
import net.mcreator.tnunlimited.item.SuperSpeedBootsItem;
import net.mcreator.tnunlimited.item.SunriseItem;
import net.mcreator.tnunlimited.item.StrawberryFoodItem;
import net.mcreator.tnunlimited.item.StoneSickleItem;
import net.mcreator.tnunlimited.item.StaffOfTheBloodgodItem;
import net.mcreator.tnunlimited.item.SporcererItem;
import net.mcreator.tnunlimited.item.SpikedCollarItem;
import net.mcreator.tnunlimited.item.SpeedBootsItem;
import net.mcreator.tnunlimited.item.SoulofadrenalineItem;
import net.mcreator.tnunlimited.item.SoulfireSpikeItem;
import net.mcreator.tnunlimited.item.SomethingItem;
import net.mcreator.tnunlimited.item.SnowgloveItem;
import net.mcreator.tnunlimited.item.SnorkleItem;
import net.mcreator.tnunlimited.item.SnagBagItem;
import net.mcreator.tnunlimited.item.SmoothieItem;
import net.mcreator.tnunlimited.item.SlothsPillowItem;
import net.mcreator.tnunlimited.item.SlothsFormulaItem;
import net.mcreator.tnunlimited.item.SlothsBedtimeElixirItem;
import net.mcreator.tnunlimited.item.SlothsBedtimeElixir3Item;
import net.mcreator.tnunlimited.item.SlothsBedtimeElixir2Item;
import net.mcreator.tnunlimited.item.SlimeSandwichItem;
import net.mcreator.tnunlimited.item.SlimeArmourItem;
import net.mcreator.tnunlimited.item.SlashProjectileItem;
import net.mcreator.tnunlimited.item.SlashProjectile2Item;
import net.mcreator.tnunlimited.item.ShiftPlateItem;
import net.mcreator.tnunlimited.item.ShieldringItem;
import net.mcreator.tnunlimited.item.SerenityItem;
import net.mcreator.tnunlimited.item.SeraphimWingsItem;
import net.mcreator.tnunlimited.item.RushringItem;
import net.mcreator.tnunlimited.item.RoseGoldRingItem;
import net.mcreator.tnunlimited.item.RoseGoldItem;
import net.mcreator.tnunlimited.item.RoseGoldIngotItem;
import net.mcreator.tnunlimited.item.RoseGoldDiscItem;
import net.mcreator.tnunlimited.item.RockItem;
import net.mcreator.tnunlimited.item.RithiumSwordItem;
import net.mcreator.tnunlimited.item.RithiumShovelItem;
import net.mcreator.tnunlimited.item.RithiumPickaxeItem;
import net.mcreator.tnunlimited.item.RithiumItem;
import net.mcreator.tnunlimited.item.RithiumHoeItem;
import net.mcreator.tnunlimited.item.RithiumAxeItem;
import net.mcreator.tnunlimited.item.RithiumArmourItem;
import net.mcreator.tnunlimited.item.RevolverItem;
import net.mcreator.tnunlimited.item.RepulsiveFlowerReplicaItem;
import net.mcreator.tnunlimited.item.ReforgedaardiumItem;
import net.mcreator.tnunlimited.item.RedPepperItem;
import net.mcreator.tnunlimited.item.RedMaulItem;
import net.mcreator.tnunlimited.item.RawtitaniumItem;
import net.mcreator.tnunlimited.item.RawRoseGoldItem;
import net.mcreator.tnunlimited.item.RawRithiumItem;
import net.mcreator.tnunlimited.item.RawLeadItem;
import net.mcreator.tnunlimited.item.RawAntimonyItem;
import net.mcreator.tnunlimited.item.RawAardiumItem;
import net.mcreator.tnunlimited.item.PurpleStickySlimeItemItem;
import net.mcreator.tnunlimited.item.ProphetItem;
import net.mcreator.tnunlimited.item.PrimalItem;
import net.mcreator.tnunlimited.item.PowerringItem;
import net.mcreator.tnunlimited.item.PlunderNBlunderbussItem;
import net.mcreator.tnunlimited.item.PlumSoupItem;
import net.mcreator.tnunlimited.item.PlumItem;
import net.mcreator.tnunlimited.item.PirateItem;
import net.mcreator.tnunlimited.item.PickaxeOfLuminescenceItem;
import net.mcreator.tnunlimited.item.PickaxeOfEffulgenceItem;
import net.mcreator.tnunlimited.item.PhaseringItem;
import net.mcreator.tnunlimited.item.PetCactusItem;
import net.mcreator.tnunlimited.item.PepperoniIngotItem;
import net.mcreator.tnunlimited.item.PepperoniFoodItem;
import net.mcreator.tnunlimited.item.PepperoniArmourItem;
import net.mcreator.tnunlimited.item.PearlItem;
import net.mcreator.tnunlimited.item.PearItem;
import net.mcreator.tnunlimited.item.PartyHatItem;
import net.mcreator.tnunlimited.item.OverchargedCleaverItem;
import net.mcreator.tnunlimited.item.OffhandFrostBulletItem;
import net.mcreator.tnunlimited.item.OffhandBulletProjectileItem;
import net.mcreator.tnunlimited.item.OceanWasteItem;
import net.mcreator.tnunlimited.item.OceanBaubleItem;
import net.mcreator.tnunlimited.item.NubriumWandItem;
import net.mcreator.tnunlimited.item.NubriumSwordItem;
import net.mcreator.tnunlimited.item.NubriumSpikeItem;
import net.mcreator.tnunlimited.item.NubriumSickleItem;
import net.mcreator.tnunlimited.item.NubriumShovelItem;
import net.mcreator.tnunlimited.item.NubriumPistolItem;
import net.mcreator.tnunlimited.item.NubriumPickaxeItem;
import net.mcreator.tnunlimited.item.NubriumItem;
import net.mcreator.tnunlimited.item.NubriumHoeItem;
import net.mcreator.tnunlimited.item.NubriumClaymoreItem;
import net.mcreator.tnunlimited.item.NubriumAxeItem;
import net.mcreator.tnunlimited.item.NubriumArmourItem;
import net.mcreator.tnunlimited.item.NitroknifeItem;
import net.mcreator.tnunlimited.item.NitroclaymoreItem;
import net.mcreator.tnunlimited.item.NitrobladeItem;
import net.mcreator.tnunlimited.item.NitroSpearItem;
import net.mcreator.tnunlimited.item.NightVisionHelmetItem;
import net.mcreator.tnunlimited.item.NetheriteWandItem;
import net.mcreator.tnunlimited.item.NetheriteSickleItem;
import net.mcreator.tnunlimited.item.NetheriteClubItem;
import net.mcreator.tnunlimited.item.NeedleGauntletItem;
import net.mcreator.tnunlimited.item.MugItem;
import net.mcreator.tnunlimited.item.MrTilesHeadOnAStickItem;
import net.mcreator.tnunlimited.item.MochaItem;
import net.mcreator.tnunlimited.item.MiracleRuneItem;
import net.mcreator.tnunlimited.item.LighterItem;
import net.mcreator.tnunlimited.item.LeadWandItem;
import net.mcreator.tnunlimited.item.LeadSwordItem;
import net.mcreator.tnunlimited.item.LeadSpikeItem;
import net.mcreator.tnunlimited.item.LeadSickleItem;
import net.mcreator.tnunlimited.item.LeadShovelItem;
import net.mcreator.tnunlimited.item.LeadPickaxeItem;
import net.mcreator.tnunlimited.item.LeadIngotItem;
import net.mcreator.tnunlimited.item.LeadHoeItem;
import net.mcreator.tnunlimited.item.LeadClubItem;
import net.mcreator.tnunlimited.item.LeadBulletItem;
import net.mcreator.tnunlimited.item.LeadBandItem;
import net.mcreator.tnunlimited.item.LeadAxeItem;
import net.mcreator.tnunlimited.item.LeadArmorItem;
import net.mcreator.tnunlimited.item.LadyBugShellItem;
import net.mcreator.tnunlimited.item.KysItem;
import net.mcreator.tnunlimited.item.KnightsBladeItem;
import net.mcreator.tnunlimited.item.KnifeSaberItem;
import net.mcreator.tnunlimited.item.KkoreulBulletItem;
import net.mcreator.tnunlimited.item.KiwiSoupItem;
import net.mcreator.tnunlimited.item.KiwiItem;
import net.mcreator.tnunlimited.item.KatanaItem;
import net.mcreator.tnunlimited.item.JarOfInfiniteJellybeansItem;
import net.mcreator.tnunlimited.item.IronWandItem;
import net.mcreator.tnunlimited.item.IronSpikeItem;
import net.mcreator.tnunlimited.item.IronSickleItem;
import net.mcreator.tnunlimited.item.IronClubItem;
import net.mcreator.tnunlimited.item.IronBandItem;
import net.mcreator.tnunlimited.item.IceballItem;
import net.mcreator.tnunlimited.item.IceSwordItem;
import net.mcreator.tnunlimited.item.HotchocolateItem;
import net.mcreator.tnunlimited.item.HotPotatoItem;
import net.mcreator.tnunlimited.item.HoneybeeIdolItem;
import net.mcreator.tnunlimited.item.HolyRelicItem;
import net.mcreator.tnunlimited.item.HematiteInfusedAnchorItem;
import net.mcreator.tnunlimited.item.HelmetFireballItem;
import net.mcreator.tnunlimited.item.HellfireWandItem;
import net.mcreator.tnunlimited.item.HellfireItem;
import net.mcreator.tnunlimited.item.HeatwaveItem;
import net.mcreator.tnunlimited.item.HeartringItem;
import net.mcreator.tnunlimited.item.HeartcoreItem;
import net.mcreator.tnunlimited.item.HamburgerItem;
import net.mcreator.tnunlimited.item.GraniteItem;
import net.mcreator.tnunlimited.item.GraniteClubItem;
import net.mcreator.tnunlimited.item.GoldenHamburgerItem;
import net.mcreator.tnunlimited.item.GoldenFeatherItem;
import net.mcreator.tnunlimited.item.GoldenEggItem;
import net.mcreator.tnunlimited.item.GoldenCrownItem;
import net.mcreator.tnunlimited.item.GoldenCactusPetItem;
import net.mcreator.tnunlimited.item.GoldWandItem;
import net.mcreator.tnunlimited.item.GoldSpikeItem;
import net.mcreator.tnunlimited.item.GoldSickleItem;
import net.mcreator.tnunlimited.item.GluttonysCleaverItem;
import net.mcreator.tnunlimited.item.GlassSkullItem;
import net.mcreator.tnunlimited.item.GlacierGlaiveItem;
import net.mcreator.tnunlimited.item.GildedChainmailPickaxeItem;
import net.mcreator.tnunlimited.item.GamblersLuckyCoinItem;
import net.mcreator.tnunlimited.item.GalvanizedSwordItem;
import net.mcreator.tnunlimited.item.GalvanizedSickleItem;
import net.mcreator.tnunlimited.item.GalvanizedShovelItem;
import net.mcreator.tnunlimited.item.GalvanizedPickaxeItem;
import net.mcreator.tnunlimited.item.GalvanizedHoeItem;
import net.mcreator.tnunlimited.item.GalvanizedHarpoonItem;
import net.mcreator.tnunlimited.item.GalvanizedClubItem;
import net.mcreator.tnunlimited.item.GalvanizedAxeItem;
import net.mcreator.tnunlimited.item.GalvanizedAirTankItem;
import net.mcreator.tnunlimited.item.FuryHookItem;
import net.mcreator.tnunlimited.item.FrostmouthItem;
import net.mcreator.tnunlimited.item.FrostburnSphereItem;
import net.mcreator.tnunlimited.item.FrostSpikeItem;
import net.mcreator.tnunlimited.item.FrostPupaeAttackItem;
import net.mcreator.tnunlimited.item.FrostBulletProjectileItem;
import net.mcreator.tnunlimited.item.FrostBulletItem;
import net.mcreator.tnunlimited.item.FrenchtoastItem;
import net.mcreator.tnunlimited.item.FloatringItem;
import net.mcreator.tnunlimited.item.FlintlockItem;
import net.mcreator.tnunlimited.item.FleurBandItem;
import net.mcreator.tnunlimited.item.FlashringItem;
import net.mcreator.tnunlimited.item.FlameringItem;
import net.mcreator.tnunlimited.item.FerrotitaniumItem;
import net.mcreator.tnunlimited.item.FeralHuntingKnifeItem;
import net.mcreator.tnunlimited.item.FancyPantsItem;
import net.mcreator.tnunlimited.item.EyeofanticipationItem;
import net.mcreator.tnunlimited.item.ExtenderItem;
import net.mcreator.tnunlimited.item.EnterTheFogItem;
import net.mcreator.tnunlimited.item.EnemySignalItem;
import net.mcreator.tnunlimited.item.EnchantedScrollOfUnbreakingItem;
import net.mcreator.tnunlimited.item.EnchantedScrollOfSmiteItem;
import net.mcreator.tnunlimited.item.EnchantedScrollOfSharpnessItem;
import net.mcreator.tnunlimited.item.EnchantedScrollOfLootingItem;
import net.mcreator.tnunlimited.item.EnchantedScrollOfFortuneItem;
import net.mcreator.tnunlimited.item.EnchantedScrollOfEfficiencyItem;
import net.mcreator.tnunlimited.item.EnchantedScrollOfBOAItem;
import net.mcreator.tnunlimited.item.EnchantedGoldenCactusPetItem;
import net.mcreator.tnunlimited.item.DryoutDiscItem;
import net.mcreator.tnunlimited.item.DoneItem;
import net.mcreator.tnunlimited.item.DoneArmourItem;
import net.mcreator.tnunlimited.item.DioriteSpearItem;
import net.mcreator.tnunlimited.item.DioriteItem;
import net.mcreator.tnunlimited.item.DiamondWandItem;
import net.mcreator.tnunlimited.item.DiamondSpikeItem;
import net.mcreator.tnunlimited.item.DiamondSickleItem;
import net.mcreator.tnunlimited.item.DiamondClubItem;
import net.mcreator.tnunlimited.item.Desert_RoachArmorItem;
import net.mcreator.tnunlimited.item.DesertIngotItem;
import net.mcreator.tnunlimited.item.DesertChitinItem;
import net.mcreator.tnunlimited.item.DecayedClawItem;
import net.mcreator.tnunlimited.item.DecardialNecklaceItem;
import net.mcreator.tnunlimited.item.DarkWarhammerItem;
import net.mcreator.tnunlimited.item.CutlassItem;
import net.mcreator.tnunlimited.item.CrownOfPrideItem;
import net.mcreator.tnunlimited.item.CriticalSwordItem;
import net.mcreator.tnunlimited.item.CoronersPlateItem;
import net.mcreator.tnunlimited.item.CookedbaconItem;
import net.mcreator.tnunlimited.item.CookedEggItem;
import net.mcreator.tnunlimited.item.ContractItem;
import net.mcreator.tnunlimited.item.CoffeeItem;
import net.mcreator.tnunlimited.item.CoffeeFruitItem;
import net.mcreator.tnunlimited.item.CoffeeBeansItem;
import net.mcreator.tnunlimited.item.CloudBootsItem;
import net.mcreator.tnunlimited.item.CherryItem;
import net.mcreator.tnunlimited.item.ChainmailPickaxeItem;
import net.mcreator.tnunlimited.item.CardialCharmItem;
import net.mcreator.tnunlimited.item.CaptainsHatItem;
import net.mcreator.tnunlimited.item.CakeblobammoItem;
import net.mcreator.tnunlimited.item.CakeblobItem;
import net.mcreator.tnunlimited.item.BulletProjectileItem;
import net.mcreator.tnunlimited.item.BulletItem;
import net.mcreator.tnunlimited.item.BuckshotPelletProjectileItem;
import net.mcreator.tnunlimited.item.BucklerItem;
import net.mcreator.tnunlimited.item.BubbleringItem;
import net.mcreator.tnunlimited.item.BomeenClubItem;
import net.mcreator.tnunlimited.item.BomaindSickleItem;
import net.mcreator.tnunlimited.item.BlunderbussItem;
import net.mcreator.tnunlimited.item.BlueShroomSapphireItem;
import net.mcreator.tnunlimited.item.BlueBerryItem;
import net.mcreator.tnunlimited.item.BloodyRapierItem;
import net.mcreator.tnunlimited.item.BloodripSpikeItem;
import net.mcreator.tnunlimited.item.BloodripItem;
import net.mcreator.tnunlimited.item.BloodgodOrbItem;
import net.mcreator.tnunlimited.item.BleedingHeartCharmItem;
import net.mcreator.tnunlimited.item.BitterDesireItem;
import net.mcreator.tnunlimited.item.BirthdayBlockBoyItem;
import net.mcreator.tnunlimited.item.BedrockCoinItem;
import net.mcreator.tnunlimited.item.BandOfBeatdownItem;
import net.mcreator.tnunlimited.item.BagOfTwoHundredKidneysItem;
import net.mcreator.tnunlimited.item.BaconItem;
import net.mcreator.tnunlimited.item.AntimonyWandItem;
import net.mcreator.tnunlimited.item.AntimonyToolsSwordItem;
import net.mcreator.tnunlimited.item.AntimonyToolsShovelItem;
import net.mcreator.tnunlimited.item.AntimonyToolsPickaxeItem;
import net.mcreator.tnunlimited.item.AntimonyToolsHoeItem;
import net.mcreator.tnunlimited.item.AntimonyToolsAxeItem;
import net.mcreator.tnunlimited.item.AntimonyStenItem;
import net.mcreator.tnunlimited.item.AntimonySickleItem;
import net.mcreator.tnunlimited.item.AntimonyItem;
import net.mcreator.tnunlimited.item.AntimonyClubItem;
import net.mcreator.tnunlimited.item.AntimonyBallItem;
import net.mcreator.tnunlimited.item.AntimonyArmorArmorItem;
import net.mcreator.tnunlimited.item.AntBladeItem;
import net.mcreator.tnunlimited.item.AmuletOfSpiteItem;
import net.mcreator.tnunlimited.item.AmethystWandItem;
import net.mcreator.tnunlimited.item.AmethystFireballItem;
import net.mcreator.tnunlimited.item.AirTankItem;
import net.mcreator.tnunlimited.item.AarduimswordItem;
import net.mcreator.tnunlimited.item.AardiumpickaxeItem;
import net.mcreator.tnunlimited.item.AardiumingotItem;
import net.mcreator.tnunlimited.item.AardiumingoShovelItem;
import net.mcreator.tnunlimited.item.AardiumingoHoeItem;
import net.mcreator.tnunlimited.item.AardiumingoAxeItem;
import net.mcreator.tnunlimited.item.AardiumWandItem;
import net.mcreator.tnunlimited.item.AardiumSickleItem;
import net.mcreator.tnunlimited.item.AardiumNeedleItem;
import net.mcreator.tnunlimited.item.AardiumItem;
import net.mcreator.tnunlimited.item.AardiumClubItem;
import net.mcreator.tnunlimited.TnunlimitedMod;

public class TnunlimitedModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, TnunlimitedMod.MODID);
	public static final RegistryObject<Item> AARDUIMSWORD = REGISTRY.register("aarduimsword", () -> new AarduimswordItem());
	public static final RegistryObject<Item> REFORGEDAARDIUM = REGISTRY.register("reforgedaardium", () -> new ReforgedaardiumItem());
	public static final RegistryObject<Item> GALVANIZED_SWORD = REGISTRY.register("galvanized_sword", () -> new GalvanizedSwordItem());
	public static final RegistryObject<Item> RITHIUM_SWORD = REGISTRY.register("rithium_sword", () -> new RithiumSwordItem());
	public static final RegistryObject<Item> LEAD_SWORD = REGISTRY.register("lead_sword", () -> new LeadSwordItem());
	public static final RegistryObject<Item> ANTIMONY_TOOLS_SWORD = REGISTRY.register("antimony_tools_sword", () -> new AntimonyToolsSwordItem());
	public static final RegistryObject<Item> NUBRIUM_SWORD = REGISTRY.register("nubrium_sword", () -> new NubriumSwordItem());
	public static final RegistryObject<Item> NUBRIUM_CLAYMORE = REGISTRY.register("nubrium_claymore", () -> new NubriumClaymoreItem());
	public static final RegistryObject<Item> KATANA = REGISTRY.register("katana", () -> new KatanaItem());
	public static final RegistryObject<Item> KNIGHTS_BLADE = REGISTRY.register("knights_blade", () -> new KnightsBladeItem());
	public static final RegistryObject<Item> SERENITY = REGISTRY.register("serenity", () -> new SerenityItem());
	public static final RegistryObject<Item> CRITICAL_SWORD = REGISTRY.register("critical_sword", () -> new CriticalSwordItem());
	public static final RegistryObject<Item> BLOODY_RAPIER = REGISTRY.register("bloody_rapier", () -> new BloodyRapierItem());
	public static final RegistryObject<Item> ZOMBIE_SWORD = REGISTRY.register("zombie_sword", () -> new ZombieSwordItem());
	public static final RegistryObject<Item> KNIFE_SABER = REGISTRY.register("knife_saber", () -> new KnifeSaberItem());
	public static final RegistryObject<Item> SWORD_SABER = REGISTRY.register("sword_saber", () -> new SwordSaberItem());
	public static final RegistryObject<Item> ICE_SWORD = REGISTRY.register("ice_sword", () -> new IceSwordItem());
	public static final RegistryObject<Item> NITROKNIFE = REGISTRY.register("nitroknife", () -> new NitroknifeItem());
	public static final RegistryObject<Item> NITROBLADE = REGISTRY.register("nitroblade", () -> new NitrobladeItem());
	public static final RegistryObject<Item> NITROCLAYMORE = REGISTRY.register("nitroclaymore", () -> new NitroclaymoreItem());
	public static final RegistryObject<Item> CUTLASS = REGISTRY.register("cutlass", () -> new CutlassItem());
	public static final RegistryObject<Item> HEATWAVE = REGISTRY.register("heatwave", () -> new HeatwaveItem());
	public static final RegistryObject<Item> WOODEN_SICKLE = REGISTRY.register("wooden_sickle", () -> new WoodenSickleItem());
	public static final RegistryObject<Item> STONE_SICKLE = REGISTRY.register("stone_sickle", () -> new StoneSickleItem());
	public static final RegistryObject<Item> IRON_SICKLE = REGISTRY.register("iron_sickle", () -> new IronSickleItem());
	public static final RegistryObject<Item> GOLD_SICKLE = REGISTRY.register("gold_sickle", () -> new GoldSickleItem());
	public static final RegistryObject<Item> AARDIUM_SICKLE = REGISTRY.register("aardium_sickle", () -> new AardiumSickleItem());
	public static final RegistryObject<Item> DIAMOND_SICKLE = REGISTRY.register("diamond_sickle", () -> new DiamondSickleItem());
	public static final RegistryObject<Item> NETHERITE_SICKLE = REGISTRY.register("netherite_sickle", () -> new NetheriteSickleItem());
	public static final RegistryObject<Item> BOMAIND_SICKLE = REGISTRY.register("bomaind_sickle", () -> new BomaindSickleItem());
	public static final RegistryObject<Item> LEAD_SICKLE = REGISTRY.register("lead_sickle", () -> new LeadSickleItem());
	public static final RegistryObject<Item> ANTIMONY_SICKLE = REGISTRY.register("antimony_sickle", () -> new AntimonySickleItem());
	public static final RegistryObject<Item> NUBRIUM_SICKLE = REGISTRY.register("nubrium_sickle", () -> new NubriumSickleItem());
	public static final RegistryObject<Item> GRANITE_CLUB = REGISTRY.register("granite_club", () -> new GraniteClubItem());
	public static final RegistryObject<Item> IRON_CLUB = REGISTRY.register("iron_club", () -> new IronClubItem());
	public static final RegistryObject<Item> AARDIUM_CLUB = REGISTRY.register("aardium_club", () -> new AardiumClubItem());
	public static final RegistryObject<Item> DIAMOND_CLUB = REGISTRY.register("diamond_club", () -> new DiamondClubItem());
	public static final RegistryObject<Item> GALVANIZED_CLUB = REGISTRY.register("galvanized_club", () -> new GalvanizedClubItem());
	public static final RegistryObject<Item> BOMEEN_CLUB = REGISTRY.register("bomeen_club", () -> new BomeenClubItem());
	public static final RegistryObject<Item> NETHERITE_CLUB = REGISTRY.register("netherite_club", () -> new NetheriteClubItem());
	public static final RegistryObject<Item> LEAD_CLUB = REGISTRY.register("lead_club", () -> new LeadClubItem());
	public static final RegistryObject<Item> ANTIMONY_CLUB = REGISTRY.register("antimony_club", () -> new AntimonyClubItem());
	public static final RegistryObject<Item> DARK_WARHAMMER = REGISTRY.register("dark_warhammer", () -> new DarkWarhammerItem());
	public static final RegistryObject<Item> DIORITE_SPEAR = REGISTRY.register("diorite_spear", () -> new DioriteSpearItem());
	public static final RegistryObject<Item> NITRO_SPEAR = REGISTRY.register("nitro_spear", () -> new NitroSpearItem());
	public static final RegistryObject<Item> GLACIER_GLAIVE = REGISTRY.register("glacier_glaive", () -> new GlacierGlaiveItem());
	public static final RegistryObject<Item> ROCK = REGISTRY.register("rock", () -> new RockItem());
	public static final RegistryObject<Item> SNOWGLOVE = REGISTRY.register("snowglove", () -> new SnowgloveItem());
	public static final RegistryObject<Item> ROSE_GOLD_DISC = REGISTRY.register("rose_gold_disc", () -> new RoseGoldDiscItem());
	public static final RegistryObject<Item> GALVANIZED_HARPOON = REGISTRY.register("galvanized_harpoon", () -> new GalvanizedHarpoonItem());
	public static final RegistryObject<Item> AMETHYST_WAND = REGISTRY.register("amethyst_wand", () -> new AmethystWandItem());
	public static final RegistryObject<Item> IRON_WAND = REGISTRY.register("iron_wand", () -> new IronWandItem());
	public static final RegistryObject<Item> GOLD_WAND = REGISTRY.register("gold_wand", () -> new GoldWandItem());
	public static final RegistryObject<Item> AARDIUM_WAND = REGISTRY.register("aardium_wand", () -> new AardiumWandItem());
	public static final RegistryObject<Item> DIAMOND_WAND = REGISTRY.register("diamond_wand", () -> new DiamondWandItem());
	public static final RegistryObject<Item> NETHERITE_WAND = REGISTRY.register("netherite_wand", () -> new NetheriteWandItem());
	public static final RegistryObject<Item> LEAD_WAND = REGISTRY.register("lead_wand", () -> new LeadWandItem());
	public static final RegistryObject<Item> ANTIMONY_WAND = REGISTRY.register("antimony_wand", () -> new AntimonyWandItem());
	public static final RegistryObject<Item> NUBRIUM_WAND = REGISTRY.register("nubrium_wand", () -> new NubriumWandItem());
	public static final RegistryObject<Item> BLOODRIP = REGISTRY.register("bloodrip", () -> new BloodripItem());
	public static final RegistryObject<Item> STAFF_OF_THE_BLOODGOD = REGISTRY.register("staff_of_the_bloodgod", () -> new StaffOfTheBloodgodItem());
	public static final RegistryObject<Item> HELLFIRE_WAND = REGISTRY.register("hellfire_wand", () -> new HellfireWandItem());
	public static final RegistryObject<Item> FROSTMOUTH = REGISTRY.register("frostmouth", () -> new FrostmouthItem());
	public static final RegistryObject<Item> BULLET = REGISTRY.register("bullet", () -> new BulletItem());
	public static final RegistryObject<Item> FLINTLOCK = REGISTRY.register("flintlock", () -> new FlintlockItem());
	public static final RegistryObject<Item> REVOLVER = REGISTRY.register("revolver", () -> new RevolverItem());
	public static final RegistryObject<Item> ANTIMONY_STEN = REGISTRY.register("antimony_sten", () -> new AntimonyStenItem());
	public static final RegistryObject<Item> NUBRIUM_PISTOL = REGISTRY.register("nubrium_pistol", () -> new NubriumPistolItem());
	public static final RegistryObject<Item> BLUNDERBUSS = REGISTRY.register("blunderbuss", () -> new BlunderbussItem());
	public static final RegistryObject<Item> LIGHTER = REGISTRY.register("lighter", () -> new LighterItem());
	public static final RegistryObject<Item> BLEEDING_HEART_CHARM = REGISTRY.register("bleeding_heart_charm", () -> new BleedingHeartCharmItem());
	public static final RegistryObject<Item> HEARTRING = REGISTRY.register("heartring", () -> new HeartringItem());
	public static final RegistryObject<Item> FLAMERING = REGISTRY.register("flamering", () -> new FlameringItem());
	public static final RegistryObject<Item> PHASERING = REGISTRY.register("phasering", () -> new PhaseringItem());
	public static final RegistryObject<Item> SHIELDRING = REGISTRY.register("shieldring", () -> new ShieldringItem());
	public static final RegistryObject<Item> FLASHRING = REGISTRY.register("flashring", () -> new FlashringItem());
	public static final RegistryObject<Item> BUBBLERING = REGISTRY.register("bubblering", () -> new BubbleringItem());
	public static final RegistryObject<Item> RUSHRING = REGISTRY.register("rushring", () -> new RushringItem());
	public static final RegistryObject<Item> FLOATRING = REGISTRY.register("floatring", () -> new FloatringItem());
	public static final RegistryObject<Item> BUCKLER = REGISTRY.register("buckler", () -> new BucklerItem());
	public static final RegistryObject<Item> GRANITE_HELMET = REGISTRY.register("granite_helmet", () -> new GraniteItem.Helmet());
	public static final RegistryObject<Item> GRANITE_CHESTPLATE = REGISTRY.register("granite_chestplate", () -> new GraniteItem.Chestplate());
	public static final RegistryObject<Item> GRANITE_LEGGINGS = REGISTRY.register("granite_leggings", () -> new GraniteItem.Leggings());
	public static final RegistryObject<Item> GRANITE_BOOTS = REGISTRY.register("granite_boots", () -> new GraniteItem.Boots());
	public static final RegistryObject<Item> DIORITE_HELMET = REGISTRY.register("diorite_helmet", () -> new DioriteItem.Helmet());
	public static final RegistryObject<Item> DIORITE_CHESTPLATE = REGISTRY.register("diorite_chestplate", () -> new DioriteItem.Chestplate());
	public static final RegistryObject<Item> DIORITE_LEGGINGS = REGISTRY.register("diorite_leggings", () -> new DioriteItem.Leggings());
	public static final RegistryObject<Item> DIORITE_BOOTS = REGISTRY.register("diorite_boots", () -> new DioriteItem.Boots());
	public static final RegistryObject<Item> WITCH_HELMET = REGISTRY.register("witch_helmet", () -> new WitchItem.Helmet());
	public static final RegistryObject<Item> WITCH_CHESTPLATE = REGISTRY.register("witch_chestplate", () -> new WitchItem.Chestplate());
	public static final RegistryObject<Item> WITCH_LEGGINGS = REGISTRY.register("witch_leggings", () -> new WitchItem.Leggings());
	public static final RegistryObject<Item> WITCH_BOOTS = REGISTRY.register("witch_boots", () -> new WitchItem.Boots());
	public static final RegistryObject<Item> PRIMAL_HELMET = REGISTRY.register("primal_helmet", () -> new PrimalItem.Helmet());
	public static final RegistryObject<Item> PRIMAL_CHESTPLATE = REGISTRY.register("primal_chestplate", () -> new PrimalItem.Chestplate());
	public static final RegistryObject<Item> PRIMAL_LEGGINGS = REGISTRY.register("primal_leggings", () -> new PrimalItem.Leggings());
	public static final RegistryObject<Item> PRIMAL_BOOTS = REGISTRY.register("primal_boots", () -> new PrimalItem.Boots());
	public static final RegistryObject<Item> ROSE_GOLD_HELMET = REGISTRY.register("rose_gold_helmet", () -> new RoseGoldItem.Helmet());
	public static final RegistryObject<Item> ROSE_GOLD_CHESTPLATE = REGISTRY.register("rose_gold_chestplate", () -> new RoseGoldItem.Chestplate());
	public static final RegistryObject<Item> ROSE_GOLD_LEGGINGS = REGISTRY.register("rose_gold_leggings", () -> new RoseGoldItem.Leggings());
	public static final RegistryObject<Item> ROSE_GOLD_BOOTS = REGISTRY.register("rose_gold_boots", () -> new RoseGoldItem.Boots());
	public static final RegistryObject<Item> AARDIUM_HELMET = REGISTRY.register("aardium_helmet", () -> new AardiumItem.Helmet());
	public static final RegistryObject<Item> AARDIUM_CHESTPLATE = REGISTRY.register("aardium_chestplate", () -> new AardiumItem.Chestplate());
	public static final RegistryObject<Item> AARDIUM_LEGGINGS = REGISTRY.register("aardium_leggings", () -> new AardiumItem.Leggings());
	public static final RegistryObject<Item> AARDIUM_BOOTS = REGISTRY.register("aardium_boots", () -> new AardiumItem.Boots());
	public static final RegistryObject<Item> ZINC_ARMOR_HELMET = REGISTRY.register("zinc_armor_helmet", () -> new ZincArmorItem.Helmet());
	public static final RegistryObject<Item> ZINC_ARMOR_CHESTPLATE = REGISTRY.register("zinc_armor_chestplate", () -> new ZincArmorItem.Chestplate());
	public static final RegistryObject<Item> ZINC_ARMOR_LEGGINGS = REGISTRY.register("zinc_armor_leggings", () -> new ZincArmorItem.Leggings());
	public static final RegistryObject<Item> ZINC_ARMOR_BOOTS = REGISTRY.register("zinc_armor_boots", () -> new ZincArmorItem.Boots());
	public static final RegistryObject<Item> RITHIUM_ARMOUR_HELMET = REGISTRY.register("rithium_armour_helmet", () -> new RithiumArmourItem.Helmet());
	public static final RegistryObject<Item> RITHIUM_ARMOUR_CHESTPLATE = REGISTRY.register("rithium_armour_chestplate", () -> new RithiumArmourItem.Chestplate());
	public static final RegistryObject<Item> RITHIUM_ARMOUR_LEGGINGS = REGISTRY.register("rithium_armour_leggings", () -> new RithiumArmourItem.Leggings());
	public static final RegistryObject<Item> RITHIUM_ARMOUR_BOOTS = REGISTRY.register("rithium_armour_boots", () -> new RithiumArmourItem.Boots());
	public static final RegistryObject<Item> DONE_ARMOUR_HELMET = REGISTRY.register("done_armour_helmet", () -> new DoneArmourItem.Helmet());
	public static final RegistryObject<Item> DONE_ARMOUR_CHESTPLATE = REGISTRY.register("done_armour_chestplate", () -> new DoneArmourItem.Chestplate());
	public static final RegistryObject<Item> DONE_ARMOUR_LEGGINGS = REGISTRY.register("done_armour_leggings", () -> new DoneArmourItem.Leggings());
	public static final RegistryObject<Item> DONE_ARMOUR_BOOTS = REGISTRY.register("done_armour_boots", () -> new DoneArmourItem.Boots());
	public static final RegistryObject<Item> LEAD_ARMOR_HELMET = REGISTRY.register("lead_armor_helmet", () -> new LeadArmorItem.Helmet());
	public static final RegistryObject<Item> LEAD_ARMOR_CHESTPLATE = REGISTRY.register("lead_armor_chestplate", () -> new LeadArmorItem.Chestplate());
	public static final RegistryObject<Item> LEAD_ARMOR_LEGGINGS = REGISTRY.register("lead_armor_leggings", () -> new LeadArmorItem.Leggings());
	public static final RegistryObject<Item> LEAD_ARMOR_BOOTS = REGISTRY.register("lead_armor_boots", () -> new LeadArmorItem.Boots());
	public static final RegistryObject<Item> DESERT_ROACH_ARMOR_HELMET = REGISTRY.register("desert_roach_armor_helmet", () -> new Desert_RoachArmorItem.Helmet());
	public static final RegistryObject<Item> DESERT_ROACH_ARMOR_CHESTPLATE = REGISTRY.register("desert_roach_armor_chestplate", () -> new Desert_RoachArmorItem.Chestplate());
	public static final RegistryObject<Item> DESERT_ROACH_ARMOR_LEGGINGS = REGISTRY.register("desert_roach_armor_leggings", () -> new Desert_RoachArmorItem.Leggings());
	public static final RegistryObject<Item> DESERT_ROACH_ARMOR_BOOTS = REGISTRY.register("desert_roach_armor_boots", () -> new Desert_RoachArmorItem.Boots());
	public static final RegistryObject<Item> ANTIMONY_ARMOR_ARMOR_HELMET = REGISTRY.register("antimony_armor_armor_helmet", () -> new AntimonyArmorArmorItem.Helmet());
	public static final RegistryObject<Item> ANTIMONY_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("antimony_armor_armor_chestplate", () -> new AntimonyArmorArmorItem.Chestplate());
	public static final RegistryObject<Item> ANTIMONY_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("antimony_armor_armor_leggings", () -> new AntimonyArmorArmorItem.Leggings());
	public static final RegistryObject<Item> ANTIMONY_ARMOR_ARMOR_BOOTS = REGISTRY.register("antimony_armor_armor_boots", () -> new AntimonyArmorArmorItem.Boots());
	public static final RegistryObject<Item> NUBRIUM_ARMOUR_HELMET = REGISTRY.register("nubrium_armour_helmet", () -> new NubriumArmourItem.Helmet());
	public static final RegistryObject<Item> NUBRIUM_ARMOUR_CHESTPLATE = REGISTRY.register("nubrium_armour_chestplate", () -> new NubriumArmourItem.Chestplate());
	public static final RegistryObject<Item> NUBRIUM_ARMOUR_LEGGINGS = REGISTRY.register("nubrium_armour_leggings", () -> new NubriumArmourItem.Leggings());
	public static final RegistryObject<Item> NUBRIUM_ARMOUR_BOOTS = REGISTRY.register("nubrium_armour_boots", () -> new NubriumArmourItem.Boots());
	public static final RegistryObject<Item> SLIME_ARMOUR_HELMET = REGISTRY.register("slime_armour_helmet", () -> new SlimeArmourItem.Helmet());
	public static final RegistryObject<Item> SLIME_ARMOUR_CHESTPLATE = REGISTRY.register("slime_armour_chestplate", () -> new SlimeArmourItem.Chestplate());
	public static final RegistryObject<Item> SLIME_ARMOUR_LEGGINGS = REGISTRY.register("slime_armour_leggings", () -> new SlimeArmourItem.Leggings());
	public static final RegistryObject<Item> SLIME_ARMOUR_BOOTS = REGISTRY.register("slime_armour_boots", () -> new SlimeArmourItem.Boots());
	public static final RegistryObject<Item> SPORCERER_HELMET = REGISTRY.register("sporcerer_helmet", () -> new SporcererItem.Helmet());
	public static final RegistryObject<Item> SPORCERER_CHESTPLATE = REGISTRY.register("sporcerer_chestplate", () -> new SporcererItem.Chestplate());
	public static final RegistryObject<Item> SPORCERER_LEGGINGS = REGISTRY.register("sporcerer_leggings", () -> new SporcererItem.Leggings());
	public static final RegistryObject<Item> SPORCERER_BOOTS = REGISTRY.register("sporcerer_boots", () -> new SporcererItem.Boots());
	public static final RegistryObject<Item> TRAIN_HELMET = REGISTRY.register("train_helmet", () -> new TrainItem.Helmet());
	public static final RegistryObject<Item> TRAIN_CHESTPLATE = REGISTRY.register("train_chestplate", () -> new TrainItem.Chestplate());
	public static final RegistryObject<Item> TRAIN_LEGGINGS = REGISTRY.register("train_leggings", () -> new TrainItem.Leggings());
	public static final RegistryObject<Item> TRAIN_BOOTS = REGISTRY.register("train_boots", () -> new TrainItem.Boots());
	public static final RegistryObject<Item> SOMETHING_HELMET = REGISTRY.register("something_helmet", () -> new SomethingItem.Helmet());
	public static final RegistryObject<Item> SOMETHING_CHESTPLATE = REGISTRY.register("something_chestplate", () -> new SomethingItem.Chestplate());
	public static final RegistryObject<Item> SOMETHING_LEGGINGS = REGISTRY.register("something_leggings", () -> new SomethingItem.Leggings());
	public static final RegistryObject<Item> SOMETHING_BOOTS = REGISTRY.register("something_boots", () -> new SomethingItem.Boots());
	public static final RegistryObject<Item> FANCY_PANTS_LEGGINGS = REGISTRY.register("fancy_pants_leggings", () -> new FancyPantsItem.Leggings());
	public static final RegistryObject<Item> GOLDEN_CROWN_HELMET = REGISTRY.register("golden_crown_helmet", () -> new GoldenCrownItem.Helmet());
	public static final RegistryObject<Item> NIGHT_VISION_HELMET_HELMET = REGISTRY.register("night_vision_helmet_helmet", () -> new NightVisionHelmetItem.Helmet());
	public static final RegistryObject<Item> PEPPERONI_ARMOUR_HELMET = REGISTRY.register("pepperoni_armour_helmet", () -> new PepperoniArmourItem.Helmet());
	public static final RegistryObject<Item> ENCHANTED_SCROLL_OF_SHARPNESS = REGISTRY.register("enchanted_scroll_of_sharpness", () -> new EnchantedScrollOfSharpnessItem());
	public static final RegistryObject<Item> ENCHANTED_SCROLL_OF_SMITE = REGISTRY.register("enchanted_scroll_of_smite", () -> new EnchantedScrollOfSmiteItem());
	public static final RegistryObject<Item> ENCHANTED_SCROLL_OF_LOOTING = REGISTRY.register("enchanted_scroll_of_looting", () -> new EnchantedScrollOfLootingItem());
	public static final RegistryObject<Item> ENCHANTED_SCROLL_OF_BOA = REGISTRY.register("enchanted_scroll_of_boa", () -> new EnchantedScrollOfBOAItem());
	public static final RegistryObject<Item> ENCHANTED_SCROLL_OF_UNBREAKING = REGISTRY.register("enchanted_scroll_of_unbreaking", () -> new EnchantedScrollOfUnbreakingItem());
	public static final RegistryObject<Item> ENCHANTED_SCROLL_OF_FORTUNE = REGISTRY.register("enchanted_scroll_of_fortune", () -> new EnchantedScrollOfFortuneItem());
	public static final RegistryObject<Item> ENCHANTED_SCROLL_OF_EFFICIENCY = REGISTRY.register("enchanted_scroll_of_efficiency", () -> new EnchantedScrollOfEfficiencyItem());
	public static final RegistryObject<Item> PIRATE_HELMET = REGISTRY.register("pirate_helmet", () -> new PirateItem.Helmet());
	public static final RegistryObject<Item> PIRATE_CHESTPLATE = REGISTRY.register("pirate_chestplate", () -> new PirateItem.Chestplate());
	public static final RegistryObject<Item> CAPTAINS_HAT_HELMET = REGISTRY.register("captains_hat_helmet", () -> new CaptainsHatItem.Helmet());
	public static final RegistryObject<Item> SERAPHIM_WINGS_CHESTPLATE = REGISTRY.register("seraphim_wings_chestplate", () -> new SeraphimWingsItem.Chestplate());
	public static final RegistryObject<Item> BIRTHDAY_BLOCK_BOY_HELMET = REGISTRY.register("birthday_block_boy_helmet", () -> new BirthdayBlockBoyItem.Helmet());
	public static final RegistryObject<Item> PARTY_HAT_HELMET = REGISTRY.register("party_hat_helmet", () -> new PartyHatItem.Helmet());
	public static final RegistryObject<Item> PROPHET_HELMET = REGISTRY.register("prophet_helmet", () -> new ProphetItem.Helmet());
	public static final RegistryObject<Item> TOP_HAT_HELMET = REGISTRY.register("top_hat_helmet", () -> new TopHatItem.Helmet());
	public static final RegistryObject<Item> AARDIUMORE = block(TnunlimitedModBlocks.AARDIUMORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DEEPAARDIUM = block(TnunlimitedModBlocks.DEEPAARDIUM, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLOCKOF_AARDIUM = block(TnunlimitedModBlocks.BLOCKOF_AARDIUM, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLOCK_OF_RAW_ROSE_GOLD = block(TnunlimitedModBlocks.BLOCK_OF_RAW_ROSE_GOLD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLOCK_OF_ROSE_GOLD = block(TnunlimitedModBlocks.BLOCK_OF_ROSE_GOLD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> ZINC_ORE = block(TnunlimitedModBlocks.ZINC_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> ZINC_DEEPSLATE_ORE = block(TnunlimitedModBlocks.ZINC_DEEPSLATE_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> ZINC_BLOCK = block(TnunlimitedModBlocks.ZINC_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NETHER_RITHIUM_ORE = block(TnunlimitedModBlocks.NETHER_RITHIUM_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RAW_RITHIUM_BLOCK = block(TnunlimitedModBlocks.RAW_RITHIUM_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RITHIUM_BLOCK = block(TnunlimitedModBlocks.RITHIUM_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> LEAD_ORE = block(TnunlimitedModBlocks.LEAD_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DEEPSLATE_LEAD_ORE = block(TnunlimitedModBlocks.DEEPSLATE_LEAD_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLOCKOFRAWLEAD = block(TnunlimitedModBlocks.BLOCKOFRAWLEAD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLOCK_OF_LEAD = block(TnunlimitedModBlocks.BLOCK_OF_LEAD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> ANTIMONY_ORE = block(TnunlimitedModBlocks.ANTIMONY_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DEEPSLATE_ANTINOMY_ORE = block(TnunlimitedModBlocks.DEEPSLATE_ANTINOMY_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLOCK_OF_RAW_ANTIMONY = block(TnunlimitedModBlocks.BLOCK_OF_RAW_ANTIMONY, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLOCK_OF_ANTIMONY = block(TnunlimitedModBlocks.BLOCK_OF_ANTIMONY, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NUBRIUM_ORE = block(TnunlimitedModBlocks.NUBRIUM_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NUBRIUM_BLOCK = block(TnunlimitedModBlocks.NUBRIUM_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> SUPERGRANITE = block(TnunlimitedModBlocks.SUPERGRANITE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PURIFIEDENERGY = block(TnunlimitedModBlocks.PURIFIEDENERGY, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DONE_BLOCK = block(TnunlimitedModBlocks.DONE_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> TITANIUMORE = block(TnunlimitedModBlocks.TITANIUMORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> LEMONSTONE = block(TnunlimitedModBlocks.LEMONSTONE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> POLISHED_LEMONSTONE = block(TnunlimitedModBlocks.POLISHED_LEMONSTONE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CHISELED_LEMONSTONE = block(TnunlimitedModBlocks.CHISELED_LEMONSTONE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> LEMONSTONE_SLAB = block(TnunlimitedModBlocks.LEMONSTONE_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> LEMONSTONE_STAIRS = block(TnunlimitedModBlocks.LEMONSTONE_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> POLISHED_LEMONSTONE_SLAB = block(TnunlimitedModBlocks.POLISHED_LEMONSTONE_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> POLISHED_LEMONSTONE_STAIRS = block(TnunlimitedModBlocks.POLISHED_LEMONSTONE_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PALM_WOOD_WOOD = block(TnunlimitedModBlocks.PALM_WOOD_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PALM_WOOD_LOG = block(TnunlimitedModBlocks.PALM_WOOD_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> COCONUT = block(TnunlimitedModBlocks.COCONUT, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLUE_SHROOM_STEM = block(TnunlimitedModBlocks.BLUE_SHROOM_STEM, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLUE_SHROOM_BLOCK = block(TnunlimitedModBlocks.BLUE_SHROOM_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GLOWINGICE = block(TnunlimitedModBlocks.GLOWINGICE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> COOKIE_BLOCK = block(TnunlimitedModBlocks.COOKIE_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RAW_ROSE_GOLD = REGISTRY.register("raw_rose_gold", () -> new RawRoseGoldItem());
	public static final RegistryObject<Item> ROSE_GOLD_INGOT = REGISTRY.register("rose_gold_ingot", () -> new RoseGoldIngotItem());
	public static final RegistryObject<Item> RAW_AARDIUM = REGISTRY.register("raw_aardium", () -> new RawAardiumItem());
	public static final RegistryObject<Item> AARDIUMINGOT = REGISTRY.register("aardiumingot", () -> new AardiumingotItem());
	public static final RegistryObject<Item> ZINC_SHEET = REGISTRY.register("zinc_sheet", () -> new ZincSheetItem());
	public static final RegistryObject<Item> ZINC_INGOT = REGISTRY.register("zinc_ingot", () -> new ZincIngotItem());
	public static final RegistryObject<Item> RAW_RITHIUM = REGISTRY.register("raw_rithium", () -> new RawRithiumItem());
	public static final RegistryObject<Item> RITHIUM = REGISTRY.register("rithium", () -> new RithiumItem());
	public static final RegistryObject<Item> RAW_LEAD = REGISTRY.register("raw_lead", () -> new RawLeadItem());
	public static final RegistryObject<Item> LEAD_INGOT = REGISTRY.register("lead_ingot", () -> new LeadIngotItem());
	public static final RegistryObject<Item> DACITE = block(TnunlimitedModBlocks.DACITE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RAW_ANTIMONY = REGISTRY.register("raw_antimony", () -> new RawAntimonyItem());
	public static final RegistryObject<Item> DACITE_SLAB = block(TnunlimitedModBlocks.DACITE_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> ANTIMONY = REGISTRY.register("antimony", () -> new AntimonyItem());
	public static final RegistryObject<Item> DACITE_STAIRS = block(TnunlimitedModBlocks.DACITE_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> NUBRIUM = REGISTRY.register("nubrium", () -> new NubriumItem());
	public static final RegistryObject<Item> COBBLED_DACITE = block(TnunlimitedModBlocks.COBBLED_DACITE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RAWTITANIUM = REGISTRY.register("rawtitanium", () -> new RawtitaniumItem());
	public static final RegistryObject<Item> COBBLED_DACITE_SLAB = block(TnunlimitedModBlocks.COBBLED_DACITE_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> TITANIUM = REGISTRY.register("titanium", () -> new TitaniumItem());
	public static final RegistryObject<Item> COBBLED_DACITE_STAIRS = block(TnunlimitedModBlocks.COBBLED_DACITE_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> FERROTITANIUM = REGISTRY.register("ferrotitanium", () -> new FerrotitaniumItem());
	public static final RegistryObject<Item> POLISHED_DACITE = block(TnunlimitedModBlocks.POLISHED_DACITE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DESERT_CHITIN = REGISTRY.register("desert_chitin", () -> new DesertChitinItem());
	public static final RegistryObject<Item> POLISHED_DACITE_SLAB = block(TnunlimitedModBlocks.POLISHED_DACITE_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DESERT_INGOT = REGISTRY.register("desert_ingot", () -> new DesertIngotItem());
	public static final RegistryObject<Item> POLISHED_DACITE_STAIRS = block(TnunlimitedModBlocks.POLISHED_DACITE_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DONE = REGISTRY.register("done", () -> new DoneItem());
	public static final RegistryObject<Item> DACITE_BRICKS = block(TnunlimitedModBlocks.DACITE_BRICKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PEPPERONI_INGOT = REGISTRY.register("pepperoni_ingot", () -> new PepperoniIngotItem());
	public static final RegistryObject<Item> DACITE_BRICKS_SLAB = block(TnunlimitedModBlocks.DACITE_BRICKS_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PEARL = REGISTRY.register("pearl", () -> new PearlItem());
	public static final RegistryObject<Item> DACITE_BRICKS_STAIRS = block(TnunlimitedModBlocks.DACITE_BRICKS_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> LADY_BUG_SHELL = REGISTRY.register("lady_bug_shell", () -> new LadyBugShellItem());
	public static final RegistryObject<Item> CRACKED_DACITE_BRICKS = block(TnunlimitedModBlocks.CRACKED_DACITE_BRICKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DECAYED_CLAW = REGISTRY.register("decayed_claw", () -> new DecayedClawItem());
	public static final RegistryObject<Item> DACITE_WALL = block(TnunlimitedModBlocks.DACITE_WALL, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> MUG = REGISTRY.register("mug", () -> new MugItem());
	public static final RegistryObject<Item> COBBLED_DACITE_WALL = block(TnunlimitedModBlocks.COBBLED_DACITE_WALL, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> WASTELANDISH_HOPPER_SPAWN_EGG = REGISTRY.register("wastelandish_hopper_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.WASTELANDISH_HOPPER, -14739442, -12504291, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> POLISHED_DACITE_WALL = block(TnunlimitedModBlocks.POLISHED_DACITE_WALL, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> LADY_BUG_ENTITY_SPAWN_EGG = REGISTRY.register("lady_bug_entity_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.LADY_BUG_ENTITY, -8912896, -15335424, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> DACITE_BRICKS_WALL = block(TnunlimitedModBlocks.DACITE_BRICKS_WALL, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> QUEEN_LADY_BUG_SPAWN_EGG = REGISTRY.register("queen_lady_bug_spawn_egg", () -> new ForgeSpawnEggItem(TnunlimitedModEntities.QUEEN_LADY_BUG, -1, -1, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> COAL_TREADLING_SPAWN_EGG = REGISTRY.register("coal_treadling_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.COAL_TREADLING, -12961222, -16053493, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> LAPIS_TREADLING_SPAWN_EGG = REGISTRY.register("lapis_treadling_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.LAPIS_TREADLING, -12961222, -16772097, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> REDSTONE_TREADLING_SPAWN_EGG = REGISTRY.register("redstone_treadling_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.REDSTONE_TREADLING, -12961222, -65536, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> PIRANHA_SPAWN_EGG = REGISTRY.register("piranha_spawn_egg", () -> new ForgeSpawnEggItem(TnunlimitedModEntities.PIRANHA, -39424, -10066330, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> CAKEMONSTER_SPAWN_EGG = REGISTRY.register("cakemonster_spawn_egg", () -> new ForgeSpawnEggItem(TnunlimitedModEntities.CAKEMONSTER, -10079488, -1, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> PINACATE_BEETLE_SPAWN_EGG = REGISTRY.register("pinacate_beetle_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.PINACATE_BEETLE, -14870249, -3441, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> DUNE_SPIDER_SPAWN_EGG = REGISTRY.register("dune_spider_spawn_egg", () -> new ForgeSpawnEggItem(TnunlimitedModEntities.DUNE_SPIDER, -8773888, -3127296, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> PIRATE_CREWMAN_SPAWN_EGG = REGISTRY.register("pirate_crewman_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.PIRATE_CREWMAN, -10482419, -13482450, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> PIRATE_DEADEYE_SPAWN_EGG = REGISTRY.register("pirate_deadeye_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.PIRATE_DEADEYE, -10482419, -13482450, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> PIRATE_CAPTAIN_SPAWN_EGG = REGISTRY.register("pirate_captain_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.PIRATE_CAPTAIN, -15193325, -4512218, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> COFFEE_POT_BUG_1_SPAWN_EGG = REGISTRY.register("coffee_pot_bug_1_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.COFFEE_POT_BUG_1, -10476800, -13753574, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> TORCH_OF_GUIDANCE = REGISTRY.register("torch_of_guidance", () -> new TorchOfGuidanceItem());
	public static final RegistryObject<Item> HOT_POTATO = REGISTRY.register("hot_potato", () -> new HotPotatoItem());
	public static final RegistryObject<Item> SUNRISE = REGISTRY.register("sunrise", () -> new SunriseItem());
	public static final RegistryObject<Item> THE_DRAGON_GUARDING_THE_ABYSS = REGISTRY.register("the_dragon_guarding_the_abyss", () -> new TheDragonGuardingTheAbyssItem());
	public static final RegistryObject<Item> WITHER_AND_ROT = REGISTRY.register("wither_and_rot", () -> new WitherAndRotItem());
	public static final RegistryObject<Item> WITHER_AND_ROT_CHIPTUNE = REGISTRY.register("wither_and_rot_chiptune", () -> new WitherAndRotChiptuneItem());
	public static final RegistryObject<Item> PLUNDER_N_BLUNDERBUSS = REGISTRY.register("plunder_n_blunderbuss", () -> new PlunderNBlunderbussItem());
	public static final RegistryObject<Item> TREE_BARK_DISC = REGISTRY.register("tree_bark_disc", () -> new TreeBarkDiscItem());
	public static final RegistryObject<Item> COFFEE_BEANS = REGISTRY.register("coffee_beans", () -> new CoffeeBeansItem());
	public static final RegistryObject<Item> GOLDEN_EGG = REGISTRY.register("golden_egg", () -> new GoldenEggItem());
	public static final RegistryObject<Item> AARDIUMPICKAXE = REGISTRY.register("aardiumpickaxe", () -> new AardiumpickaxeItem());
	public static final RegistryObject<Item> AARDIUMINGO_AXE = REGISTRY.register("aardiumingo_axe", () -> new AardiumingoAxeItem());
	public static final RegistryObject<Item> AARDIUMINGO_SHOVEL = REGISTRY.register("aardiumingo_shovel", () -> new AardiumingoShovelItem());
	public static final RegistryObject<Item> AARDIUMINGO_HOE = REGISTRY.register("aardiumingo_hoe", () -> new AardiumingoHoeItem());
	public static final RegistryObject<Item> GALVANIZED_PICKAXE = REGISTRY.register("galvanized_pickaxe", () -> new GalvanizedPickaxeItem());
	public static final RegistryObject<Item> GALVANIZED_AXE = REGISTRY.register("galvanized_axe", () -> new GalvanizedAxeItem());
	public static final RegistryObject<Item> GALVANIZED_SHOVEL = REGISTRY.register("galvanized_shovel", () -> new GalvanizedShovelItem());
	public static final RegistryObject<Item> GALVANIZED_HOE = REGISTRY.register("galvanized_hoe", () -> new GalvanizedHoeItem());
	public static final RegistryObject<Item> RITHIUM_PICKAXE = REGISTRY.register("rithium_pickaxe", () -> new RithiumPickaxeItem());
	public static final RegistryObject<Item> RITHIUM_AXE = REGISTRY.register("rithium_axe", () -> new RithiumAxeItem());
	public static final RegistryObject<Item> RITHIUM_SHOVEL = REGISTRY.register("rithium_shovel", () -> new RithiumShovelItem());
	public static final RegistryObject<Item> RITHIUM_HOE = REGISTRY.register("rithium_hoe", () -> new RithiumHoeItem());
	public static final RegistryObject<Item> LEAD_PICKAXE = REGISTRY.register("lead_pickaxe", () -> new LeadPickaxeItem());
	public static final RegistryObject<Item> LEAD_AXE = REGISTRY.register("lead_axe", () -> new LeadAxeItem());
	public static final RegistryObject<Item> LEAD_SHOVEL = REGISTRY.register("lead_shovel", () -> new LeadShovelItem());
	public static final RegistryObject<Item> LEAD_HOE = REGISTRY.register("lead_hoe", () -> new LeadHoeItem());
	public static final RegistryObject<Item> ANTIMONY_TOOLS_PICKAXE = REGISTRY.register("antimony_tools_pickaxe", () -> new AntimonyToolsPickaxeItem());
	public static final RegistryObject<Item> ANTIMONY_TOOLS_AXE = REGISTRY.register("antimony_tools_axe", () -> new AntimonyToolsAxeItem());
	public static final RegistryObject<Item> ANTIMONY_TOOLS_SHOVEL = REGISTRY.register("antimony_tools_shovel", () -> new AntimonyToolsShovelItem());
	public static final RegistryObject<Item> ANTIMONY_TOOLS_HOE = REGISTRY.register("antimony_tools_hoe", () -> new AntimonyToolsHoeItem());
	public static final RegistryObject<Item> NUBRIUM_PICKAXE = REGISTRY.register("nubrium_pickaxe", () -> new NubriumPickaxeItem());
	public static final RegistryObject<Item> NUBRIUM_SHOVEL = REGISTRY.register("nubrium_shovel", () -> new NubriumShovelItem());
	public static final RegistryObject<Item> NUBRIUM_AXE = REGISTRY.register("nubrium_axe", () -> new NubriumAxeItem());
	public static final RegistryObject<Item> NUBRIUM_HOE = REGISTRY.register("nubrium_hoe", () -> new NubriumHoeItem());
	public static final RegistryObject<Item> CHAINMAIL_PICKAXE = REGISTRY.register("chainmail_pickaxe", () -> new ChainmailPickaxeItem());
	public static final RegistryObject<Item> GILDED_CHAINMAIL_PICKAXE = REGISTRY.register("gilded_chainmail_pickaxe", () -> new GildedChainmailPickaxeItem());
	public static final RegistryObject<Item> PICKAXE_OF_LUMINESCENCE = REGISTRY.register("pickaxe_of_luminescence", () -> new PickaxeOfLuminescenceItem());
	public static final RegistryObject<Item> PICKAXE_OF_EFFULGENCE = REGISTRY.register("pickaxe_of_effulgence", () -> new PickaxeOfEffulgenceItem());
	public static final RegistryObject<Item> FLEUR_BAND = REGISTRY.register("fleur_band", () -> new FleurBandItem());
	public static final RegistryObject<Item> IRON_BAND = REGISTRY.register("iron_band", () -> new IronBandItem());
	public static final RegistryObject<Item> REPULSIVE_FLOWER_REPLICA = REGISTRY.register("repulsive_flower_replica", () -> new RepulsiveFlowerReplicaItem());
	public static final RegistryObject<Item> PET_CACTUS = REGISTRY.register("pet_cactus", () -> new PetCactusItem());
	public static final RegistryObject<Item> GOLDEN_CACTUS_PET = REGISTRY.register("golden_cactus_pet", () -> new GoldenCactusPetItem());
	public static final RegistryObject<Item> ENCHANTED_GOLDEN_CACTUS_PET = REGISTRY.register("enchanted_golden_cactus_pet", () -> new EnchantedGoldenCactusPetItem());
	public static final RegistryObject<Item> SPEED_BOOTS = REGISTRY.register("speed_boots", () -> new SpeedBootsItem());
	public static final RegistryObject<Item> SUPER_SPEED_BOOTS = REGISTRY.register("super_speed_boots", () -> new SuperSpeedBootsItem());
	public static final RegistryObject<Item> ROSE_GOLD_RING = REGISTRY.register("rose_gold_ring", () -> new RoseGoldRingItem());
	public static final RegistryObject<Item> CARDIAL_CHARM = REGISTRY.register("cardial_charm", () -> new CardialCharmItem());
	public static final RegistryObject<Item> HEARTCORE = REGISTRY.register("heartcore", () -> new HeartcoreItem());
	public static final RegistryObject<Item> DECARDIAL_NECKLACE = REGISTRY.register("decardial_necklace", () -> new DecardialNecklaceItem());
	public static final RegistryObject<Item> MIRACLE_RUNE = REGISTRY.register("miracle_rune", () -> new MiracleRuneItem());
	public static final RegistryObject<Item> NEEDLE_GAUNTLET = REGISTRY.register("needle_gauntlet", () -> new NeedleGauntletItem());
	public static final RegistryObject<Item> TINY_SELF_DETONATOR = REGISTRY.register("tiny_self_detonator", () -> new TinySelfDetonatorItem());
	public static final RegistryObject<Item> WRATHS_DEATH_CRY = REGISTRY.register("wraths_death_cry", () -> new WrathsDeathCryItem());
	public static final RegistryObject<Item> GLASS_SKULL_HELMET = REGISTRY.register("glass_skull_helmet", () -> new GlassSkullItem.Helmet());
	public static final RegistryObject<Item> SLOTHS_PILLOW = REGISTRY.register("sloths_pillow", () -> new SlothsPillowItem());
	public static final RegistryObject<Item> CONTRACT = REGISTRY.register("contract", () -> new ContractItem());
	public static final RegistryObject<Item> HONEYBEE_IDOL = REGISTRY.register("honeybee_idol", () -> new HoneybeeIdolItem());
	public static final RegistryObject<Item> HOLY_RELIC = REGISTRY.register("holy_relic", () -> new HolyRelicItem());
	public static final RegistryObject<Item> GOLDEN_FEATHER = REGISTRY.register("golden_feather", () -> new GoldenFeatherItem());
	public static final RegistryObject<Item> LEAD_BAND = REGISTRY.register("lead_band", () -> new LeadBandItem());
	public static final RegistryObject<Item> BAND_OF_BEATDOWN = REGISTRY.register("band_of_beatdown", () -> new BandOfBeatdownItem());
	public static final RegistryObject<Item> CLOUD_BOOTS = REGISTRY.register("cloud_boots", () -> new CloudBootsItem());
	public static final RegistryObject<Item> OCEAN_BAUBLE = REGISTRY.register("ocean_bauble", () -> new OceanBaubleItem());
	public static final RegistryObject<Item> GAMBLERS_LUCKY_COIN = REGISTRY.register("gamblers_lucky_coin", () -> new GamblersLuckyCoinItem());
	public static final RegistryObject<Item> EXTENDER = REGISTRY.register("extender", () -> new ExtenderItem());
	public static final RegistryObject<Item> HEMATITE_INFUSED_ANCHOR = REGISTRY.register("hematite_infused_anchor", () -> new HematiteInfusedAnchorItem());
	public static final RegistryObject<Item> SHIFT_PLATE = REGISTRY.register("shift_plate", () -> new ShiftPlateItem());
	public static final RegistryObject<Item> SPIKED_COLLAR = REGISTRY.register("spiked_collar", () -> new SpikedCollarItem());
	public static final RegistryObject<Item> TWO_LAYER_HELMET_HELMET = REGISTRY.register("two_layer_helmet_helmet", () -> new TwoLayerHelmetItem.Helmet());
	public static final RegistryObject<Item> SOULOFADRENALINE = REGISTRY.register("soulofadrenaline", () -> new SoulofadrenalineItem());
	public static final RegistryObject<Item> AMULET_OF_SPITE = REGISTRY.register("amulet_of_spite", () -> new AmuletOfSpiteItem());
	public static final RegistryObject<Item> COFFEE_PLANT = block(TnunlimitedModBlocks.COFFEE_PLANT, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> MIRESHROOM = block(TnunlimitedModBlocks.MIRESHROOM, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> TALL_MIRESHROOM = doubleBlock(TnunlimitedModBlocks.TALL_MIRESHROOM, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> OVERDRIVE_TABLE = block(TnunlimitedModBlocks.OVERDRIVE_TABLE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> SPAWNING_EYE = block(TnunlimitedModBlocks.SPAWNING_EYE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PLUSH_AARDVARKMAN = block(TnunlimitedModBlocks.PLUSH_AARDVARKMAN, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PLUSH_PURPLE_KNIGHT = block(TnunlimitedModBlocks.PLUSH_PURPLE_KNIGHT, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PLUSH_HIVEMASTER = block(TnunlimitedModBlocks.PLUSH_HIVEMASTER, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PLUSH_GLOWING_GOLEM = block(TnunlimitedModBlocks.PLUSH_GLOWING_GOLEM, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PLUSH_ANIME_RACOON = block(TnunlimitedModBlocks.PLUSH_ANIME_RACOON, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PLUSH_STOATMAN = block(TnunlimitedModBlocks.PLUSH_STOATMAN, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> COFFEE_FRUIT = REGISTRY.register("coffee_fruit", () -> new CoffeeFruitItem());
	public static final RegistryObject<Item> COFFEE = REGISTRY.register("coffee", () -> new CoffeeItem());
	public static final RegistryObject<Item> HOTCHOCOLATE = REGISTRY.register("hotchocolate", () -> new HotchocolateItem());
	public static final RegistryObject<Item> MOCHA = REGISTRY.register("mocha", () -> new MochaItem());
	public static final RegistryObject<Item> HAMBURGER = REGISTRY.register("hamburger", () -> new HamburgerItem());
	public static final RegistryObject<Item> GOLDEN_HAMBURGER = REGISTRY.register("golden_hamburger", () -> new GoldenHamburgerItem());
	public static final RegistryObject<Item> BACON = REGISTRY.register("bacon", () -> new BaconItem());
	public static final RegistryObject<Item> COOKEDBACON = REGISTRY.register("cookedbacon", () -> new CookedbaconItem());
	public static final RegistryObject<Item> COOKED_EGG = REGISTRY.register("cooked_egg", () -> new CookedEggItem());
	public static final RegistryObject<Item> FRENCHTOAST = REGISTRY.register("frenchtoast", () -> new FrenchtoastItem());
	public static final RegistryObject<Item> STRAWBERRY_FOOD = REGISTRY.register("strawberry_food", () -> new StrawberryFoodItem());
	public static final RegistryObject<Item> PEAR = REGISTRY.register("pear", () -> new PearItem());
	public static final RegistryObject<Item> BLUE_BERRY = REGISTRY.register("blue_berry", () -> new BlueBerryItem());
	public static final RegistryObject<Item> PLUM = REGISTRY.register("plum", () -> new PlumItem());
	public static final RegistryObject<Item> RED_PEPPER = REGISTRY.register("red_pepper", () -> new RedPepperItem());
	public static final RegistryObject<Item> KIWI = REGISTRY.register("kiwi", () -> new KiwiItem());
	public static final RegistryObject<Item> CHERRY = REGISTRY.register("cherry", () -> new CherryItem());
	public static final RegistryObject<Item> KIWI_SOUP = REGISTRY.register("kiwi_soup", () -> new KiwiSoupItem());
	public static final RegistryObject<Item> PLUM_SOUP = REGISTRY.register("plum_soup", () -> new PlumSoupItem());
	public static final RegistryObject<Item> SLIME_SANDWICH = REGISTRY.register("slime_sandwich", () -> new SlimeSandwichItem());
	public static final RegistryObject<Item> PEPPERONI_FOOD = REGISTRY.register("pepperoni_food", () -> new PepperoniFoodItem());
	public static final RegistryObject<Item> JAR_OF_INFINITE_JELLYBEANS = REGISTRY.register("jar_of_infinite_jellybeans", () -> new JarOfInfiniteJellybeansItem());
	public static final RegistryObject<Item> TREE_BARK = REGISTRY.register("tree_bark", () -> new TreeBarkItem());
	public static final RegistryObject<Item> BULLET_PROJECTILE = REGISTRY.register("bullet_projectile", () -> new BulletProjectileItem());
	public static final RegistryObject<Item> BUCKSHOT_PELLET_PROJECTILE = REGISTRY.register("buckshot_pellet_projectile", () -> new BuckshotPelletProjectileItem());
	public static final RegistryObject<Item> BAG_OF_TWO_HUNDRED_KIDNEYS = REGISTRY.register("bag_of_two_hundred_kidneys", () -> new BagOfTwoHundredKidneysItem());
	public static final RegistryObject<Item> AMETHYST_FIREBALL = REGISTRY.register("amethyst_fireball", () -> new AmethystFireballItem());
	public static final RegistryObject<Item> HELLFIRE = REGISTRY.register("hellfire", () -> new HellfireItem());
	public static final RegistryObject<Item> STRAWBERRY_BUSHSTAGE_4 = block(TnunlimitedModBlocks.STRAWBERRY_BUSHSTAGE_4, null);
	public static final RegistryObject<Item> STRAWBERRY_BUSHSTAGE_3 = block(TnunlimitedModBlocks.STRAWBERRY_BUSHSTAGE_3, null);
	public static final RegistryObject<Item> STRAWBERRY_BUSHSTAGE_0 = block(TnunlimitedModBlocks.STRAWBERRY_BUSHSTAGE_0, null);
	public static final RegistryObject<Item> STRAWBERRY_BUSHSTAGE_2 = block(TnunlimitedModBlocks.STRAWBERRY_BUSHSTAGE_2, null);
	public static final RegistryObject<Item> STRAWBERRY_BUSHSTAGE_1 = block(TnunlimitedModBlocks.STRAWBERRY_BUSHSTAGE_1, null);
	public static final RegistryObject<Item> FROST_PUPAE_ATTACK = REGISTRY.register("frost_pupae_attack", () -> new FrostPupaeAttackItem());
	public static final RegistryObject<Item> HELMET_FIREBALL = REGISTRY.register("helmet_fireball", () -> new HelmetFireballItem());
	public static final RegistryObject<Item> BLOODRIP_SPIKE = REGISTRY.register("bloodrip_spike", () -> new BloodripSpikeItem());
	public static final RegistryObject<Item> MR_TILES_HEAD_ON_A_STICK = REGISTRY.register("mr_tiles_head_on_a_stick", () -> new MrTilesHeadOnAStickItem());
	public static final RegistryObject<Item> BLOODGOD_ORB = REGISTRY.register("bloodgod_orb", () -> new BloodgodOrbItem());
	public static final RegistryObject<Item> ICEBALL = REGISTRY.register("iceball", () -> new IceballItem());
	public static final RegistryObject<Item> AARDIUM_NEEDLE = REGISTRY.register("aardium_needle", () -> new AardiumNeedleItem());
	public static final RegistryObject<Item> LEAD_SPIKE = REGISTRY.register("lead_spike", () -> new LeadSpikeItem());
	public static final RegistryObject<Item> NUBRIUM_SPIKE = REGISTRY.register("nubrium_spike", () -> new NubriumSpikeItem());
	public static final RegistryObject<Item> FROSTBURN_SPHERE = REGISTRY.register("frostburn_sphere", () -> new FrostburnSphereItem());
	public static final RegistryObject<Item> GOLD_SPIKE = REGISTRY.register("gold_spike", () -> new GoldSpikeItem());
	public static final RegistryObject<Item> DIAMOND_SPIKE = REGISTRY.register("diamond_spike", () -> new DiamondSpikeItem());
	public static final RegistryObject<Item> ANTIMONY_BALL = REGISTRY.register("antimony_ball", () -> new AntimonyBallItem());
	public static final RegistryObject<Item> IRON_SPIKE = REGISTRY.register("iron_spike", () -> new IronSpikeItem());
	public static final RegistryObject<Item> SOULFIRE_SPIKE = REGISTRY.register("soulfire_spike", () -> new SoulfireSpikeItem());
	public static final RegistryObject<Item> CAKESPLATTER = block(TnunlimitedModBlocks.CAKESPLATTER, null);
	public static final RegistryObject<Item> CAKEBLOB = REGISTRY.register("cakeblob", () -> new CakeblobItem());
	public static final RegistryObject<Item> KILLER_BANANA = REGISTRY.register("killer_banana", () -> new KysItem());
	public static final RegistryObject<Item> CAKEBLOBAMMO = REGISTRY.register("cakeblobammo", () -> new CakeblobammoItem());
	public static final RegistryObject<Item> RED_MAUL = REGISTRY.register("red_maul", () -> new RedMaulItem());
	public static final RegistryObject<Item> EYEOFANTICIPATION = REGISTRY.register("eyeofanticipation", () -> new EyeofanticipationItem());
	public static final RegistryObject<Item> CROWN_OF_PRIDE = REGISTRY.register("crown_of_pride", () -> new CrownOfPrideItem());
	public static final RegistryObject<Item> WEATHER_CLOCK = REGISTRY.register("weather_clock", () -> new WeatherClockItem());
	public static final RegistryObject<Item> TANGELO_BLOSSOM = block(TnunlimitedModBlocks.TANGELO_BLOSSOM, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BITTER_DESIRE = REGISTRY.register("bitter_desire", () -> new BitterDesireItem());
	public static final RegistryObject<Item> SLOTHS_FORMULA = REGISTRY.register("sloths_formula", () -> new SlothsFormulaItem());
	public static final RegistryObject<Item> ICE_ROSE = block(TnunlimitedModBlocks.ICE_ROSE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> SLOTHS_BEDTIME_ELIXIR = REGISTRY.register("sloths_bedtime_elixir", () -> new SlothsBedtimeElixirItem());
	public static final RegistryObject<Item> SLOTHS_BEDTIME_ELIXIR_2 = REGISTRY.register("sloths_bedtime_elixir_2", () -> new SlothsBedtimeElixir2Item());
	public static final RegistryObject<Item> SLOTHS_BEDTIME_ELIXIR_3 = REGISTRY.register("sloths_bedtime_elixir_3", () -> new SlothsBedtimeElixir3Item());
	public static final RegistryObject<Item> BLUE_SHROOMSLATE = block(TnunlimitedModBlocks.BLUE_SHROOMSLATE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> SHROOM_GRASS = block(TnunlimitedModBlocks.SHROOM_GRASS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLUE_SHROOM_FUNGI = block(TnunlimitedModBlocks.BLUE_SHROOM_FUNGI, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> GLUTTONYS_CLEAVER = REGISTRY.register("gluttonys_cleaver", () -> new GluttonysCleaverItem());
	public static final RegistryObject<Item> BLUE_SHROOM_ROOTS = block(TnunlimitedModBlocks.BLUE_SHROOM_ROOTS, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BLUE_SHROOM_SAPPHIRE = REGISTRY.register("blue_shroom_sapphire", () -> new BlueShroomSapphireItem());
	public static final RegistryObject<Item> BLUE_SHROOM_ORE = block(TnunlimitedModBlocks.BLUE_SHROOM_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLUE_SHROOM_THRONS = block(TnunlimitedModBlocks.BLUE_SHROOM_THRONS, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> SNAG_BAG = REGISTRY.register("snag_bag", () -> new SnagBagItem());
	public static final RegistryObject<Item> BEDROCK_ANDY_SPAWN_EGG = REGISTRY.register("bedrock_andy_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.BEDROCK_ANDY, -13421773, -16777216, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> BEDROCK_COIN = REGISTRY.register("bedrock_coin", () -> new BedrockCoinItem());
	public static final RegistryObject<Item> PURPLE_BEETLE_SPAWN_EGG = REGISTRY.register("purple_beetle_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.PURPLE_BEETLE, -14280339, -15264993, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> PURPLE_LIGHTGLOW = block(TnunlimitedModBlocks.PURPLE_LIGHTGLOW, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> CATTAIL = doubleBlock(TnunlimitedModBlocks.CATTAIL, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BLUE_LAVANDER = doubleBlock(TnunlimitedModBlocks.BLUE_LAVANDER, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> CORONER_SPAWN_EGG = REGISTRY.register("coroner_spawn_egg", () -> new ForgeSpawnEggItem(TnunlimitedModEntities.CORONER, -16764109, -13369549, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> CORONERS_PLATE = REGISTRY.register("coroners_plate", () -> new CoronersPlateItem());
	public static final RegistryObject<Item> WARCASTER_HELMET = REGISTRY.register("warcaster_helmet", () -> new WarcasterItem.Helmet());
	public static final RegistryObject<Item> WARCASTER_CHESTPLATE = REGISTRY.register("warcaster_chestplate", () -> new WarcasterItem.Chestplate());
	public static final RegistryObject<Item> WARCASTER_LEGGINGS = REGISTRY.register("warcaster_leggings", () -> new WarcasterItem.Leggings());
	public static final RegistryObject<Item> WARCASTER_BOOTS = REGISTRY.register("warcaster_boots", () -> new WarcasterItem.Boots());
	public static final RegistryObject<Item> OFFHAND_BULLET_PROJECTILE = REGISTRY.register("offhand_bullet_projectile", () -> new OffhandBulletProjectileItem());
	public static final RegistryObject<Item> FROST_ANT_QUEEN_SPAWN_EGG = REGISTRY.register("frost_ant_queen_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.FROST_ANT_QUEEN, -6438926, -11310973, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> GALVANIZED_SICKLE = REGISTRY.register("galvanized_sickle", () -> new GalvanizedSickleItem());
	public static final RegistryObject<Item> FROST_SPIKE = REGISTRY.register("frost_spike", () -> new FrostSpikeItem());
	public static final RegistryObject<Item> SLASH_PROJECTILE = REGISTRY.register("slash_projectile", () -> new SlashProjectileItem());
	public static final RegistryObject<Item> SLASH_PROJECTILE_2 = REGISTRY.register("slash_projectile_2", () -> new SlashProjectile2Item());
	public static final RegistryObject<Item> FROST_ANT_SPAWN_EGG = REGISTRY.register("frost_ant_spawn_egg", () -> new ForgeSpawnEggItem(TnunlimitedModEntities.FROST_ANT, -1444871, -11310973, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> FROSTBURNT_SPAWN_EGG = REGISTRY.register("frostburnt_spawn_egg", () -> new ForgeSpawnEggItem(TnunlimitedModEntities.FROSTBURNT, -14866130, -10360065, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> FROST_PUPAE_SPAWN_EGG = REGISTRY.register("frost_pupae_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.FROST_PUPAE, -4928809, -13395457, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> FROST_ANT_ALATE_SPAWN_EGG = REGISTRY.register("frost_ant_alate_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.FROST_ANT_ALATE, -1444871, -13395457, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> ANT_BLADE = REGISTRY.register("ant_blade", () -> new AntBladeItem());
	public static final RegistryObject<Item> VAMBRACE = REGISTRY.register("vambrace", () -> new VambraceItem());
	public static final RegistryObject<Item> FROST_ANT_WORKER_SPAWN_EGG = REGISTRY.register("frost_ant_worker_spawn_egg",
			() -> new ForgeSpawnEggItem(TnunlimitedModEntities.FROST_ANT_WORKER, -4928809, -4350127, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> PURPLE_SHROOMSLATE_STAIRS = block(TnunlimitedModBlocks.PURPLE_SHROOMSLATE_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PURPLE_SHROOMSLATE_SLABS = block(TnunlimitedModBlocks.PURPLE_SHROOMSLATE_SLABS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> FROST_ANT_EGG_SACK = block(TnunlimitedModBlocks.FROST_ANT_EGG_SACK, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PURPLE_SHROOMSLATE_WALLS = block(TnunlimitedModBlocks.PURPLE_SHROOMSLATE_WALLS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> LEAD_BULLET = REGISTRY.register("lead_bullet", () -> new LeadBulletItem());
	public static final RegistryObject<Item> PURPLE_COBBLE_SHROOMSLATE = block(TnunlimitedModBlocks.PURPLE_COBBLE_SHROOMSLATE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PURPLE_COBBLE_SHROOMSLATE_SHAIRS = block(TnunlimitedModBlocks.PURPLE_COBBLE_SHROOMSLATE_SHAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PURPLE_COBBLE_SHROOMSLATE_SLAB = block(TnunlimitedModBlocks.PURPLE_COBBLE_SHROOMSLATE_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PURPLE_COBBLE_SHROOMSLATE_WALLS = block(TnunlimitedModBlocks.PURPLE_COBBLE_SHROOMSLATE_WALLS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> FROST_BULLET = REGISTRY.register("frost_bullet", () -> new FrostBulletItem());
	public static final RegistryObject<Item> FROST_BULLET_PROJECTILE = REGISTRY.register("frost_bullet_projectile", () -> new FrostBulletProjectileItem());
	public static final RegistryObject<Item> OFFHAND_FROST_BULLET = REGISTRY.register("offhand_frost_bullet", () -> new OffhandFrostBulletItem());
	public static final RegistryObject<Item> LEAD_BARS = block(TnunlimitedModBlocks.LEAD_BARS, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> LEAD_SPIKE_BLOCK = block(TnunlimitedModBlocks.LEAD_SPIKE_BLOCK, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> LEAD_DOOR = doubleBlock(TnunlimitedModBlocks.LEAD_DOOR, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> POLISHED_DACITE_PRESSURE_PLATE = block(TnunlimitedModBlocks.POLISHED_DACITE_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> POLISHED_DACITE_BUTTON = block(TnunlimitedModBlocks.POLISHED_DACITE_BUTTON, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> LEAD_TRAPDOOR = block(TnunlimitedModBlocks.LEAD_TRAPDOOR, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> THICK_HORSESHOE = REGISTRY.register("thick_horseshoe", () -> new ThickHorseshoeItem());
	public static final RegistryObject<Item> ENEMY_SIGNAL = REGISTRY.register("enemy_signal", () -> new EnemySignalItem());
	public static final RegistryObject<Item> KKOREUL_BULLET = REGISTRY.register("kkoreul_bullet", () -> new KkoreulBulletItem());
	public static final RegistryObject<Item> OVERCHARGED_CLEAVER = REGISTRY.register("overcharged_cleaver", () -> new OverchargedCleaverItem());
	public static final RegistryObject<Item> KKOREUL_SPAWN_EGG = REGISTRY.register("kkoreul_spawn_egg", () -> new ForgeSpawnEggItem(TnunlimitedModEntities.KKOREUL, -13421773, -6710887, new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> OCEAN_WASTE = REGISTRY.register("ocean_waste", () -> new OceanWasteItem());
	public static final RegistryObject<Item> DRYOUT_DISC = REGISTRY.register("dryout_disc", () -> new DryoutDiscItem());
	public static final RegistryObject<Item> ENTER_THE_FOG = REGISTRY.register("enter_the_fog", () -> new EnterTheFogItem());
	public static final RegistryObject<Item> SNORKLE = REGISTRY.register("snorkle", () -> new SnorkleItem());
	public static final RegistryObject<Item> AIR_TANK = REGISTRY.register("air_tank", () -> new AirTankItem());
	public static final RegistryObject<Item> GALVANIZED_AIR_TANK = REGISTRY.register("galvanized_air_tank", () -> new GalvanizedAirTankItem());
	public static final RegistryObject<Item> BLENDER = block(TnunlimitedModBlocks.BLENDER, CreativeModeTab.TAB_TRANSPORTATION);
	public static final RegistryObject<Item> SMOOTHIE = REGISTRY.register("smoothie", () -> new SmoothieItem());
	public static final RegistryObject<Item> POWERRING = REGISTRY.register("powerring", () -> new PowerringItem());
	public static final RegistryObject<Item> FURY_HOOK = REGISTRY.register("fury_hook", () -> new FuryHookItem());
	public static final RegistryObject<Item> FERAL_HUNTING_KNIFE = REGISTRY.register("feral_hunting_knife", () -> new FeralHuntingKnifeItem());
	public static final RegistryObject<Item> PURPLE_STICKY_SLIME_ITEM = REGISTRY.register("purple_sticky_slime_item", () -> new PurpleStickySlimeItemItem());
	public static final RegistryObject<Item> PURPLE_STICKY_SLIME = block(TnunlimitedModBlocks.PURPLE_STICKY_SLIME, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> WET_SAND = block(TnunlimitedModBlocks.WET_SAND, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> VILLAGER_NOSE_HELMET = REGISTRY.register("villager_nose_helmet", () -> new VillagerNoseItem.Helmet());
	public static final RegistryObject<Item> PLAM_LEAVES = block(TnunlimitedModBlocks.PLAM_LEAVES, TnunlimitedModTabs.TAB_ACCESSORIES_TAB);

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
